AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters:
  EC2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2WebServer01:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: Fn::ImportValue "PublicSubnet1ID"
      ImageId: !Ref EC2AMI
      InstanceType: t2.micro
