name: environment-from-branchname

on:
  workflow_dispatch:
  
jobs:
  environment-from-branchname:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable `BRANCH`
        shell: bash
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV 

      - name: Set  environment variable `ENVIRONMENT`
        shell: bash
        run: |
          declare -A ENVIRONMENTS=(
            ["main"]="prod"
            ["staging"]="staging"
          )
          echo "ENVIRONMENT=${ENVIRONMENTS[$BRANCH]:-"develop"}" >> $GITHUB_ENV

      - name: Echo environment variables
        shell: bash
        run: |
          echo "BRANCH:$BRANCH"
          echo "ENVIRONMENT:$ENVIRONMENT"

