name: environment-from-branchname

on:
  workflow_dispatch:
  
jobs:
  environment-from-branchname:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment name
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV 
      - name: Set environment name
        shell: bash
        run: echo $BRANCH
