name: environment-from-branchname

on:
  workflow_dispatch:
  
jobs:
  environment-from-branchname:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment name
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV 
      - name: Set environment name
        shell: bash
        run: echo $BRANCH
      - name: Set environment name2
        shell: bash
        run: |
          declare -A ENVIRONMENTS=(
            ["main"]="prod"
            ["staging"]="staging"
          )
          echo "ENVIRONMENT=${ENVIRONMENTS[$BRANCH]:-"develop"}" >> $GITHUB_ENV
      - name: Set environment name
        shell: bash
        run: echo $ENVIRONMENT

