name: releasetag

on:
  workflow_dispatch:
  
jobs:
  releasetag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 1
      - run: |
        TAG=v$(date '+%Y%m%d').$(git rev-parse --short HEAD)
        echo "${TAG}" >> $GITHUB_ENV
        shell: bash
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $TAG
          release_name: Release $TAG
          draft: false
          prerelease: false

#       - name: Tag
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git tag hoge

#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
