name: VPC

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: "Service name"
        required: true
        default: "basic-2az-network"

jobs:
  create-change-set:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #custom_tag: hoge

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: VPCStack
          template: vpc.yaml
          no-execute-changeset: 1
          parameter-overrides: "ServiceName=${{ github.event.inputs.serviceName }}"
